In [2]:
import numpy as np
from IPython.display import display
#1
#.1 צור מערך של מספרים שלמים אקראיים בגודל 4 X 4 של מספרים 1-100 )השתמש ב SEED 80 )
np.random.seed(80)
rand_array = np.random.randint(0, 101, (4, 4))
print(rand_array)

[[47 60 38 83]
 [10 50  3 86]
 [23 15 81  5]
 [64  9 92 42]]


In [3]:
#a. הדפס את כל המספרים הגדולים מ- 50 )השתמש בתנאי בתוך סוגריים מרובעים(
display('rand_array > 50 ', rand_array[(rand_array > 50)])

'rand_array > 50 '

array([60, 83, 86, 81, 64, 92])

In [8]:
#b. הדפס את סכום כל עמודה בנפרד, וכל שורה בנפרד. רמז axis
print('columns',rand_array.sum(axis=0))
print('rows',rand_array.sum(axis=1))

columns [144 134 214 216]
rows [228 149 124 207]


In [10]:
#-np.min np.max np.mean בפונקציות השתמש ,b בסעיף שפתרת כפי ,כעת .c
print('columns:')
print('min:', rand_array.min(axis=0))
print('max:', rand_array.max(axis=0))
print('mean:', rand_array.mean(axis=0))
print('rows:')
print('min:', rand_array.min(axis=1))
print('max:', rand_array.max(axis=1))
print('mean:', rand_array.mean(axis=1))

columns:
min: [10  9  3  5]
max: [64 60 92 86]
mean: [36.  33.5 53.5 54. ]
rows:
min: [38  3  5  9]
max: [83 86 81 92]
mean: [57.   37.25 31.   51.75]
